version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:${MYSQL_VERSION:-8.0.32}
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-local}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-cart}
      MYSQL_USER: ${MYSQL_USER:-test}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-test}
    volumes:
      - data_mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - "${PHP_PORT:-9001}:9000"
    volumes:
      - ./api:/home/symfony/docker
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "${PHP_PORT:-8080}:80"
    volumes:
      - ./api:/home/symfony/docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

volumes:
  data_mysql: